// Default sample template for Advanced Bill Generator
// Pure data-only export to keep page.tsx smaller. No logic changes.
import { Template } from "./advancedTypes";

export function makeDefaultSampleTemplate(): Template {
  return {
    id: "tpl-1",
    name: "Professional Invoice Template",
    description:
      "A complete invoice template with company header, client details, and itemized billing",
    width: 800,
    height: 1120,
    createdAt: new Date(),
    fields: [
      // Company Header
      {
        id: "company-name",
        label: "Company Name",
        value: "Your Company Name",
        type: "text",
        x: 50,
        y: 30,
        width: 300,
        height: 40,
        fontSize: 24,
        isBold: true,
        isItalic: false,
        textColor: "#1f2937",
        backgroundColor: "transparent",
        borderColor: "transparent",
        borderWidth: 0,
        borderRadius: 0,
        alignment: "left",
        required: true,
      },
      {
        id: "company-address",
        label: "Company Address",
        value:
          "123 Business Street\nCity, State 12345\nPhone: (555) 123-4567\nEmail: info@company.com",
        type: "textarea",
        x: 50,
        y: 80,
        width: 300,
        height: 80,
        fontSize: 12,
        isBold: false,
        isItalic: false,
        textColor: "#6b7280",
        backgroundColor: "transparent",
        borderColor: "transparent",
        borderWidth: 0,
        borderRadius: 0,
        alignment: "left",
        required: false,
      },
      // Invoice Title
      {
        id: "invoice-title",
        label: "Invoice Title",
        value: "INVOICE",
        type: "text",
        x: 500,
        y: 30,
        width: 250,
        height: 50,
        fontSize: 32,
        isBold: true,
        isItalic: false,
        textColor: "#dc2626",
        backgroundColor: "transparent",
        borderColor: "transparent",
        borderWidth: 0,
        borderRadius: 0,
        alignment: "right",
        required: true,
      },
      // Invoice Details
      {
        id: "invoice-number",
        label: "Invoice Number",
        value: "INV-001",
        type: "text",
        x: 500,
        y: 90,
        width: 250,
        height: 30,
        fontSize: 14,
        isBold: false,
        isItalic: false,
        textColor: "#374151",
        backgroundColor: "transparent",
        borderColor: "transparent",
        borderWidth: 0,
        borderRadius: 0,
        alignment: "right",
        required: true,
      },
      {
        id: "invoice-date",
        label: "Invoice Date",
        value: new Date().toLocaleDateString(),
        type: "date",
        x: 500,
        y: 130,
        width: 250,
        height: 30,
        fontSize: 14,
        isBold: false,
        isItalic: false,
        textColor: "#374151",
        backgroundColor: "transparent",
        borderColor: "transparent",
        borderWidth: 0,
        borderRadius: 0,
        alignment: "right",
        required: true,
      },
      // Bill To Section
      {
        id: "bill-to-label",
        label: "Bill To Label",
        value: "Bill To:",
        type: "text",
        x: 50,
        y: 200,
        width: 100,
        height: 30,
        fontSize: 16,
        isBold: true,
        isItalic: false,
        textColor: "#1f2937",
        backgroundColor: "transparent",
        borderColor: "transparent",
        borderWidth: 0,
        borderRadius: 0,
        alignment: "left",
        required: false,
      },
      {
        id: "client-details",
        label: "Client Details",
        value:
          "Client Company Name\nClient Address Line 1\nClient Address Line 2\nCity, State ZIP\nPhone: (555) 987-6543",
        type: "textarea",
        x: 50,
        y: 240,
        width: 350,
        height: 100,
        fontSize: 14,
        isBold: false,
        isItalic: false,
        textColor: "#374151",
        backgroundColor: "#f9fafb",
        borderColor: "#d1d5db",
        borderWidth: 1,
        borderRadius: 4,
        alignment: "left",
        required: true,
      },
      // Table Header Row
      {
        id: "header-description",
        label: "Header Description",
        value: "Description",
        type: "text",
        x: 50,
        y: 380,
        width: 350,
        height: 35,
        fontSize: 14,
        isBold: true,
        isItalic: false,
        textColor: "#ffffff",
        backgroundColor: "#4b5563",
        borderColor: "#374151",
        borderWidth: 1,
        borderRadius: 0,
        alignment: "left",
        required: false,
      },
      {
        id: "header-qty",
        label: "Header Qty",
        value: "Qty",
        type: "text",
        x: 400,
        y: 380,
        width: 80,
        height: 35,
        fontSize: 14,
        isBold: true,
        isItalic: false,
        textColor: "#ffffff",
        backgroundColor: "#4b5563",
        borderColor: "#374151",
        borderWidth: 1,
        borderRadius: 0,
        alignment: "center",
        required: false,
      },
      {
        id: "header-rate",
        label: "Header Rate",
        value: "Rate",
        type: "text",
        x: 480,
        y: 380,
        width: 120,
        height: 35,
        fontSize: 14,
        isBold: true,
        isItalic: false,
        textColor: "#ffffff",
        backgroundColor: "#4b5563",
        borderColor: "#374151",
        borderWidth: 1,
        borderRadius: 0,
        alignment: "center",
        required: false,
      },
      {
        id: "header-amount",
        label: "Header Amount",
        value: "Amount",
        type: "text",
        x: 600,
        y: 380,
        width: 150,
        height: 35,
        fontSize: 14,
        isBold: true,
        isItalic: false,
        textColor: "#ffffff",
        backgroundColor: "#4b5563",
        borderColor: "#374151",
        borderWidth: 1,
        borderRadius: 0,
        alignment: "center",
        required: false,
      },
      // Item 1 Row
      {
        id: "item1-description",
        label: "Item 1 Description",
        value: "Professional Services - Web Development",
        type: "text",
        x: 50,
        y: 415,
        width: 350,
        height: 30,
        fontSize: 12,
        isBold: false,
        isItalic: false,
        textColor: "#374151",
        backgroundColor: "#ffffff",
        borderColor: "#e5e7eb",
        borderWidth: 1,
        borderRadius: 0,
        alignment: "left",
        required: false,
      },
      {
        id: "item1-qty",
        label: "Item 1 Qty",
        value: "1",
        type: "text",
        x: 400,
        y: 415,
        width: 80,
        height: 30,
        fontSize: 12,
        isBold: false,
        isItalic: false,
        textColor: "#374151",
        backgroundColor: "#ffffff",
        borderColor: "#e5e7eb",
        borderWidth: 1,
        borderRadius: 0,
        alignment: "center",
        required: false,
      },
      {
        id: "item1-rate",
        label: "Item 1 Rate",
        value: "$1,500.00",
        type: "text",
        x: 480,
        y: 415,
        width: 120,
        height: 30,
        fontSize: 12,
        isBold: false,
        isItalic: false,
        textColor: "#374151",
        backgroundColor: "#ffffff",
        borderColor: "#e5e7eb",
        borderWidth: 1,
        borderRadius: 0,
        alignment: "right",
        required: false,
      },
      {
        id: "item1-amount",
        label: "Item 1 Amount",
        value: "$1,500.00",
        type: "text",
        x: 600,
        y: 415,
        width: 150,
        height: 30,
        fontSize: 12,
        isBold: false,
        isItalic: false,
        textColor: "#374151",
        backgroundColor: "#ffffff",
        borderColor: "#e5e7eb",
        borderWidth: 1,
        borderRadius: 0,
        alignment: "right",
        required: false,
      },
      // Item 2 Row
      {
        id: "item2-description",
        label: "Item 2 Description",
        value: "Design Consultation",
        type: "text",
        x: 50,
        y: 445,
        width: 350,
        height: 30,
        fontSize: 12,
        isBold: false,
        isItalic: false,
        textColor: "#374151",
        backgroundColor: "#f9fafb",
        borderColor: "#e5e7eb",
        borderWidth: 1,
        borderRadius: 0,
        alignment: "left",
        required: false,
      },
      {
        id: "item2-qty",
        label: "Item 2 Qty",
        value: "2",
        type: "text",
        x: 400,
        y: 445,
        width: 80,
        height: 30,
        fontSize: 12,
        isBold: false,
        isItalic: false,
        textColor: "#374151",
        backgroundColor: "#f9fafb",
        borderColor: "#e5e7eb",
        borderWidth: 1,
        borderRadius: 0,
        alignment: "center",
        required: false,
      },
      {
        id: "item2-rate",
        label: "Item 2 Rate",
        value: "$250.00",
        type: "text",
        x: 480,
        y: 445,
        width: 120,
        height: 30,
        fontSize: 12,
        isBold: false,
        isItalic: false,
        textColor: "#374151",
        backgroundColor: "#f9fafb",
        borderColor: "#e5e7eb",
        borderWidth: 1,
        borderRadius: 0,
        alignment: "right",
        required: false,
      },
      {
        id: "item2-amount",
        label: "Item 2 Amount",
        value: "$500.00",
        type: "text",
        x: 600,
        y: 445,
        width: 150,
        height: 30,
        fontSize: 12,
        isBold: false,
        isItalic: false,
        textColor: "#374151",
        backgroundColor: "#f9fafb",
        borderColor: "#e5e7eb",
        borderWidth: 1,
        borderRadius: 0,
        alignment: "right",
        required: false,
      },
      // Totals Section
      {
        id: "subtotal",
        label: "Subtotal",
        value: "Subtotal: $2,000.00",
        type: "text",
        x: 500,
        y: 520,
        width: 250,
        height: 30,
        fontSize: 14,
        isBold: false,
        isItalic: false,
        textColor: "#374151",
        backgroundColor: "transparent",
        borderColor: "transparent",
        borderWidth: 0,
        borderRadius: 0,
        alignment: "right",
        required: false,
      },
      {
        id: "tax",
        label: "Tax",
        value: "Tax (8.25%): $165.00",
        type: "text",
        x: 500,
        y: 555,
        width: 250,
        height: 30,
        fontSize: 14,
        isBold: false,
        isItalic: false,
        textColor: "#374151",
        backgroundColor: "transparent",
        borderColor: "transparent",
        borderWidth: 0,
        borderRadius: 0,
        alignment: "right",
        required: false,
      },
      {
        id: "total",
        label: "Total Amount",
        value: "Total: $2,165.00",
        type: "amount",
        x: 500,
        y: 590,
        width: 250,
        height: 40,
        fontSize: 18,
        isBold: true,
        isItalic: false,
        textColor: "#dc2626",
        backgroundColor: "#fef2f2",
        borderColor: "#dc2626",
        borderWidth: 2,
        borderRadius: 4,
        alignment: "right",
        required: true,
      },
      // Payment Terms
      {
        id: "payment-terms",
        label: "Payment Terms",
        value:
          "Payment Terms:\n• Payment is due within 30 days of invoice date\n• Late payments may incur a 1.5% monthly service charge\n• Please include invoice number with payment\n\nThank you for your business!",
        type: "textarea",
        x: 50,
        y: 680,
        width: 700,
        height: 120,
        fontSize: 12,
        isBold: false,
        isItalic: false,
        textColor: "#6b7280",
        backgroundColor: "#f9fafb",
        borderColor: "#d1d5db",
        borderWidth: 1,
        borderRadius: 4,
        alignment: "left",
        required: false,
      },
    ],
  };
}
