import { Template, TemplateField } from "@/lib/advancedTypes";

export function makeEmptyTemplate(idx: number): Template {
  const defaultFields: TemplateField[] = [
    {
      id: `fld-customer-${Date.now()}`,
      label: "Customer Name",
      value: "",
      type: "text",
      x: 100,
      y: 100,
      width: 200,
      height: 40,
      fontSize: 16,
      isBold: false,
      isItalic: false,
      textColor: "#000000",
      backgroundColor: "#ffffff",
      borderColor: "#e5e7eb",
      borderWidth: 1,
      borderRadius: 6,
      alignment: "left",
      required: true,
      subElements: [],
    },
    {
      id: `fld-date-${Date.now() + 1}`,
      label: "Date",
      value: new Date().toLocaleDateString(),
      type: "text",
      x: 600,
      y: 60,
      width: 160,
      height: 36,
      fontSize: 14,
      isBold: false,
      isItalic: false,
      textColor: "#111827",
      backgroundColor: "#ffffff",
      borderColor: "#e5e7eb",
      borderWidth: 1,
      borderRadius: 6,
      alignment: "right",
      required: true,
      subElements: [],
    },
    {
      id: `fld-logo-${Date.now() + 2}`,
      label: "Company Logo",
      value: "",
      type: "image",
      x: 40,
      y: 40,
      width: 120,
      height: 80,
      fontSize: 12,
      isBold: false,
      isItalic: false,
      textColor: "#6b7280",
      backgroundColor: "#ffffff",
      borderColor: "#e5e7eb",
      borderWidth: 1,
      borderRadius: 6,
      alignment: "center",
      required: false,
      lockAspect: true,
      subElements: [],
    },
    {
      id: `fld-total-${Date.now() + 3}`,
      label: "Total",
      value: "0.00",
      type: "text",
      x: 600,
      y: 1000,
      width: 160,
      height: 40,
      fontSize: 18,
      isBold: true,
      isItalic: false,
      textColor: "#111827",
      backgroundColor: "#ffffff",
      borderColor: "#e5e7eb",
      borderWidth: 1,
      borderRadius: 6,
      alignment: "right",
      required: true,
      subElements: [
        {
          id: `sub-total-label-${Date.now() + 4}`,
          type: "caption",
          content: "Total",
          position: "left",
          offsetX: -60,
          offsetY: 10,
          fontSize: 14,
          textColor: "#6b7280",
          isBold: false,
          isItalic: false,
        },
      ],
    },
    {
      id: `fld-signature-${Date.now() + 5}`,
      label: "Signature",
      value: "",
      type: "signature",
      x: 80,
      y: 980,
      width: 240,
      height: 80,
      fontSize: 12,
      isBold: false,
      isItalic: false,
      textColor: "#111827",
      backgroundColor: "#ffffff",
      borderColor: "#e5e7eb",
      borderWidth: 1,
      borderRadius: 6,
      alignment: "left",
      required: false,
      lockAspect: false,
      subElements: [
        {
          id: `sub-signature-label-${Date.now() + 6}`,
          type: "caption",
          content: "Customer Signature",
          position: "bottom",
          offsetX: 0,
          offsetY: 10,
          fontSize: 12,
          textColor: "#6b7280",
          isBold: false,
          isItalic: true,
        },
      ],
    },
  ];

  return {
    id: `tpl-${idx}`,
    name: `Template ${idx}`,
    description: "New advanced template with default fields",
    width: 800,
    height: 1120,
    createdAt: new Date(),
    fields: defaultFields,
  };
}

export function duplicateFromProfessional(base: Template, idx: number): Template {
  return {
    ...base,
    id: `tpl-${Date.now()}`,
    name: `${base.name} (${idx})`,
    description: base.description,
    width: base.width,
    height: base.height,
    createdAt: new Date(),
    fields: base.fields.map((f) => ({
      ...f,
      id: `${f.id}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    })),
  };
}
